pipeline {
    agent {label 'slave'}
    stages {
        stage('Checkout Stage') {
            steps {
                git url: 'https://github.com/ghoshbib/bibaswan2023.git', branch: 'jenkins'
            }
        }
        stage('Build Stage') {
            steps {
                bat "dotnet build project: 'JenkinsWebApplication/JenkinsWebApplicationDemo.sln', sdk: '.NET 6'"
            }
        }
       
        }
    }
