pipeline {
    agent any
    stages {
        stage('Checkout Stage') {
            steps {
                git url: 'https://github.com/ghoshbib/bibaswan2023.git', branch: 'jenkins'
            }
        }
        stage('Build Stage') {
            steps {
                bat "dotnet build ${WORKSPACE}\\JenkinsWebApplication\\JenkinsWebApplicationDemo\\JenkinsWebApplicationDemo.csproj -c Release -o out"
            }
        }
       
        }
    }
