pipeline {
    agent {label 'slave'}
    stages {
        stage('Checkout Stage') {
            steps {
                git url: 'https://github.com/ghoshbib/bibaswan2023.git', branch: 'jenkins'
            }
        }
        stage('Build Stage') {
            steps {
                bat "dotnet build C:\\Program Files\\dotnet\\sdk\\7.0.304\\MSBuild.dll -maxcpucount -verbosity:m -restore -consoleloggerparameters:Summary project: 'JenkinsWebApplicationDemo.sln', sdk: '.NET 6' -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\\Program Files\\dotnet\\sdk\\7.0.304\\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\\Program Files\\dotnet\\sdk\\7.0.304\\dotnet.dll"
            }
        }
       
        }
    }
